version: "3"

services:

  hapi-server:
    image: ${IMAGE}
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: ${CONTAINER_NAME}
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - .:/code
    environment:
      - NODE_HOST=${HOST}
      - NODE_PORT=${PORT}
